[project]
name = "thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sven Goerdes", email = "Sven@Goerdes.com" }
]
requires-python = ">=3.10"
dependencies = [
    "cloudpickle==3.1.2",
    "farama-notifications==0.0.4",
    "gymnasium==1.2.3",
    "neat-python==1.1.0",
    "numpy==2.2.6",
    "pygame==2.6.1",
    "pylint>=4.0.4",
    "typing-extensions==4.15.0",
]

[project.optional-dependencies]
metaworld = [
    "metaworld>=3.0.0",
]
tensorneat = [
    "jax>=0.4.28",
    "tensorneat @ git+https://github.com/EMI-Group/tensorneat.git",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true


[tool.hatch.build.targets.wheel]
packages = ["src/config", "src/evaluation", "src/training"]
